### ISSUE TITLE
Environment Configuration

### ISSUE THREAD

**Issue by Yingfei-Wu** [TaatiTeam/STARS#2]
Thank you very much for your work. We are trying to reproduce the results of your paper, but for some reason, our results are always different from those presented in your article. We suspect that this might be due to differences in the environment configuration. Could you kindly provide the information about the versions of the environment (such as PyTorch, CUDA, etc.) used in your code?

**Comment by SoroushMehraban** [comment]
Hi @mooyewu,

These are the libraries in the environment:
```
asn1crypto==0.24.0
certifi==2022.9.24
chardet==3.0.4
charset-normalizer==2.1.1
ClusterShell==1.8
command-not-found==0.3
crcmod==1.7
cryptography==2.1.4
distro-info===0.18ubuntu0.18.04.1
fail2ban==0.10.2
idna==3.4
iotop==0.6
joblib==1.1.1
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
netifaces==0.10.4
numpy==1.23.4
olefile==0.45.1
opencv-contrib-python==4.5.5.62
openslide-python==1.1.1
Pillow==9.3.0
pycrypto==2.6.1
Pygments==2.2.0
PyGObject==3.26.1
pyinotify==0.9.6
python-apt==1.6.6
pyxdg==0.25
PyYAML==3.12
requests==2.28.1
schedulefree==1.2.7
SecretStorage==2.3.1
six==1.11.0
ssh-import-id==5.7
systemd-python==234
torch==1.12.0+cu113
torchaudio==0.12.0+cu113
torchvision==0.13.0+cu113
typing_extensions==4.4.0
ubuntu-advantage-tools==8001
ufw==0.36
unattended-upgrades==0.1
urllib3==1.26.12
virtualenv==15.1.0
```

Note that during pretraining we used 4xA40 GPUs. So batch_size of 32 in the config means that the effective batch size is 128.
